### ISSUE TITLE
active set initialization

### ISSUE THREAD

**Issue by zhaofeng-shu33** [Zagrosss/maxflow#2]
In the current code base, `_active` array maintains the current active nodes ( which means it has some excess and can push its flow to neighboring nodes). This array is initialized to all nodes of the graph, which I think can be further refined to a small subset.

**Comment by Zagrosss** [comment]
Which algorithm are you reffering to?
All data structures are preallocated before any given algorithm starts in order to avoid reallocations. You could indeed start with a smaller array and expand it during runtime if necessary, but it would introduce some overhead.

**Comment by zhaofeng-shu33** [comment]
Sorry for the incomplete information. I refer to `parallel_push_relabel` algorithm.

**Comment by zhaofeng-shu33** [comment]
I think it is feasible to use some prior knowledge to initiate `_active` array instead of invoking `global_relabel` specifically at the beginning of the infinite loop.

**Comment by Zagrosss** [comment]
You could just push from the source at the beginning and set all vertices (except for the source) to height 0. This is the standard way the push-relabel algorithm works. Performing the global relabel instead may yield better results however (or it may not, as it is only a heuristic).
I have measured the performance of both versions and found out that the version which performs global relabel straight away is usually faster for most inputs.

**Comment by zhaofeng-shu33** [comment]
Thanks for your comment.
