### ISSUE TITLE
double type excess in generic parallel maximum flow

### ISSUE THREAD

**Issue by zhaofeng-shu33** [Zagrosss/maxflow#4]
This issue is related with the implementation of `parallel_push_relabel.h`.

Since `std::atomic<double>` does not provide lock mechanism (no method `fetch_and_and`), it is unsafe to add the value to the new_excess structure elegantly. Any suggestions to deal with floating type capacity using this algorithm?

Reference:
https://stackoverflow.com/questions/30048533/why-isnt-atomic-double-fully-implemented

**Comment by Zagrosss** [comment]
Floating point edge capacities are not supported. Note that the DIMACS format specifies edge capacities as 32bit integers.

**Comment by zhaofeng-shu33** [comment]
ok
